name: Monatlicher Berichtsexport

on:
  schedule:
    - cron: '0 3 * * *'   # Täglich um 3 Uhr (UTC), kann z.B. auf 15. stellen: 0 3 15 * *
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Monatsberichte generieren & hochladen
        run: npm start
